### ISSUE TITLE
Card info

### ISSUE THREAD

**Issue by nosovk** [greshny/privatbank#4]
Подскажите пожалуйста, а получилось ли у вас в privatbank/p24/info по номеру карты получить ФИО плательщика?

**Comment by greshny** [comment]
К сожалению, нет возможности проверить. Как только будет доступ к приват24 я посмотрю.

**Comment by nosovk** [comment]
Я проверил просто через PostMan - API привата не возвращает ФИО поставщика

**Comment by greshny** [comment]
Тогда лучше обратиться в поддержку приватбанка, возможно ли это реализовать.

**Comment by nosovk** [comment]
уже, неделю назад. Пока молчат. Думаю нельзя.

**Comment by greshny** [comment]
We have to wait untill privat24 api will support it. ¯\_(ツ)_/¯

**Comment by nosovk** [comment]
They never answered, chat said that it's impossible. As a result made it in other way, without privat24 API
